version: '3.8'

services:

    api:
        build:
            context: .
            dockerfile: ./infrastructure/dev/node/Dockerfile
        container_name: 'capital-gains-app'
        volumes:
            - ./src:/usr/app/src
            - ./package.json:/usr/app/package.json
            - ./package-lock.json:/usr/app/package-lock.json
            - ./tsconfig.json:/usr/app/tsconfig.json
            - ./jest.config.js:/usr/app/jest.config.js
